// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omzxhtjmmwexzxyyyjyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tenhodGptbXdleHp4eXl5anlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODgzNTksImV4cCI6MjA3MzY2NDM1OX0.YADl7F09PnqsvhKJK6UNFeTKn53_IdYvar16zuLcwEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});